;NAME: SOURAV CHANDRA DEY
;REGD NO: 2141004133

;OBJ2: ARRANGE ELEMENTS OF A GIVEN ARRAY OF SIZE N IN ASCENDING ORDER

.DATA
    COUNT DB 04H
    VALUE DB 0FH, 09H, 14H, 01H

.CODE
MAIN PROC 
    MOV AX, DATA
    MOV DS, AX
    MOV CL, COUNT
    DEC CL
UP2:MOV CH, CL
    LEA SI, VALUE
UP1:MOV AL, [SI]
    CMP AL, [SI+1]
    JC DN
    MOV DL, [SI+1]
    XCHG [SI], DL
    MOV [SI+1], DL
 DN:INC SI
    DEC CH
    JNZ UP1
    DEC CL
    JNZ UP2 
   END MAIN
